# Generated by Django 2.1 on 2019-09-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_ops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='subLocation',
            field=models.OneToOneField(on_delete='', to='db_ops.Location'),
        ),
    ]
