# Generated by Django 2.1 on 2019-09-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_ops', '0002_auto_20190910_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='subLocation',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete='', to='db_ops.Location'),
        ),
    ]
